name: Upload Python Package

on:
  push:
    tags:
      - "v*" # Push events to matching v*, i.e. v1.0, v20.15.10

permissions:
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install the latest version of rye
        uses: eifinger/setup-rye@v4.2.2

      - name: Set up Python
        uses: actions/setup-python@v5.1.1
        with:
          python-version: "3.x"

      - name: Build package
        run: rye build

      - name: Publish package
        run: rye publish --token "${{ secrets.PYPI_API_TOKEN }}" --yes
